Suppress goroot path in tool builds
bazelbuild/rules_go pull request #2952
Opened 2021-09-15 03:31 UTC by adobke

The goroot is encoded in the output binary, but the goroot is different
in different workspaces. As a result tool binaries (such as builder) are
not reproducible. Bazel will have cache misses for build involving
builder even if the resulting output from the build is reproducible.

Similar to go_binary builds, suppress the goroot path in go_tool_binary
output so that the result in reproducible.

**What type of PR is this?**
> Bug fix

**What does this PR do? Why is it needed?**
Like go_binary output, ensure go_tool

**Which issues(s) does this PR fix?**

Fixes #2951

2021-09-15 16:01 UTC, sluongng commented
Simple fix, simple test. This change LGTM.

Very interesting find! I am very curious on how you came about and got down to troubleshooting this issue.
I tried to reproduce the issue and diffing the hex dump of the 2 builder binaries but couldnt make much sense of it.

There is a missing link somewhere between the `go_sdk` being encoded inside the binary and the `GOROOT_FINAL` being set.

I know the `GOROOT` string value was picked to be consistent with the go_binary rule, but could you confirm that the value does not matter here as long as it's a fixed non-empty string?

Thanks!

2021-09-15 21:07 UTC, steeve requested changes
Thank you! Minor nitpick regarding gofmt

2021-09-15 21:07 UTC, steeve commented on tests/integration/reproducibility/reproducibility_test.go
> +	  t.Fatal(err);
gofmt

2021-09-16 05:32 UTC, adobke commented on tests/integration/reproducibility/reproducibility_test.go
> +	  t.Fatal(err);
Ah yes of course!

2021-09-16 05:39 UTC, adobke commented
> Simple fix, simple test. This change LGTM.
> 
> Very interesting find! I am very curious on how you came about and got down to troubleshooting this issue.
> I tried to reproduce the issue and diffing the hex dump of the 2 builder binaries but couldnt make much sense of it.

Indeed one minor change in the binary seems to end up making the hex dumps totally diverge. The tool that was useful here was to compare the output of `strings` on the each binary which revealed the embedded and different paths. 

> There is a missing link somewhere between the `go_sdk` being encoded inside the binary and the `GOROOT_FINAL` being set.
> 
> I know the `GOROOT` string value was picked to be consistent with the go_binary rule, but could you confirm that the value does not matter here as long as it's a fixed non-empty string?

Confirmed, changing to a random string seemed to make not difference (e.g. all tests pass)

2021-09-22 16:20 UTC, steeve approved these changes

2021-09-22 16:20 UTC, steeve commented
Thank you! Merging

2021-09-22 16:20 UTC, merged