enable windows/arm64 go build with bazel
bazelbuild/rules_go pull request #3072
Opened 2022-02-18 10:09 UTC by nsait-linaro

**What type of PR is this?**

> Feature

**What does this PR do? Why is it needed?**

> Enable windows/arm64 go build with Bazel

**Other notes for review**

Go for windows/arm64 is available from version 17. This patch adds the missing pieces to build go programs with bazel.

2022-03-22 10:22 UTC, nsait-linaro commented
@linzhp Can you help with review please ?

2022-03-22 18:40 UTC, nsait-linaro commented on go/private/sdk.bzl
> +            goarch = "arm64"
Much better! Seems to work

2022-03-22 19:28 UTC, nsait-linaro commented
@linzhp Unfortunately, one test is failing on CI now with the latest change. Any guess? 

```
Error: 'repository_os' value has no field or method 'arch'
  | (18:42:06) ERROR: C:/b/bk-windows-k0sj/bazel/rules-go-golang/WORKSPACE:9:23: fetching _go_download_sdk rule //external:go_sdk: Traceback (most recent call last):
  | File "C:/b/sz2aij3q/external/io_bazel_rules_go/go/private/sdk.bzl", line 47, column 45, in _go_download_sdk_impl
  | goos, goarch = _detect_host_platform(ctx)
  | File "C:/b/sz2aij3q/external/io_bazel_rules_go/go/private/sdk.bzl", line 280, column 18, in _detect_host_platform
  | if ctx.os.arch == "aarch64":
  | Error: 'repository_os' value has no field or method 'arch'
 
```

2022-03-22 19:55 UTC, linzhp commented
Yeah, `repository_os.arch` is only available in main branch of Bazel, not yet available in 5.0 release. We can either wait for 5.1 release, or `ctx.os.environ.get("PROCESSOR_ARCHITECTURE")`

2022-03-22 20:18 UTC, nsait-linaro commented
> Yeah, `repository_os.arch` is only available in main branch of Bazel, not yet available in 5.0 release. We can either wait for 5.1 release, or `ctx.os.environ.get("PROCESSOR_ARCHITECTURE")`

Thanks. Shall I revert latest commit and use previous approach of using environment variables ?

2022-03-22 21:25 UTC, linzhp commented
You can decide which way you want to go

2022-03-23 12:55 UTC, nsait-linaro commented
> You can decide which way you want to go

Ok I will use env. variable for the time being.

2022-03-23 15:27 UTC, linzhp requested changes

2022-03-23 15:27 UTC, linzhp commented on go/private/sdk.bzl
> +            goarch = "arm64"
```suggestion
        goos = "windows"
        # TODO: use ctx.os.arch after minimal version of Bazel becomes 5.1.
        if ctx.os.environ.get("PROCESSOR_ARCHITECTURE") == "ARM64" or ctx.os.environ.get("PROCESSOR_ARCHITEW6432") == "ARM64":
            goarch = "arm64"
        else:
            goarch = "amd64"
```

* Avoid assigning `goarch` to "amd64" and immediately override it.
* Don't implement something that `dict` already has.

2022-03-23 17:58 UTC, merged

2022-04-05 12:32 UTC, nsait-linaro commented
@linzhp Any idea when the next release is expected? I have a related [PR](https://github.com/bazelbuild/bazelisk/pull/302) for bazelisk that can be applied only after rules_go release