[go_proto_library] File granularity for output groups in OutputGroupInfo
bazelbuild/rules_go pull request #3667
Opened 2023-08-22 07:05 UTC by tingilee

**What type of PR is this?**

> Feature

**What does this PR do? Why is it needed?**

Make OutputGroupInfo more modularized in go_proto_library. This allows us to create filegroups referring to subset of the generated Go files. 

**Which issues(s) does this PR fix?**

Fixes #3664

**Other notes for review**

2023-08-22 07:56 UTC, fmeum requested changes

2023-08-22 07:56 UTC, fmeum commented on proto/def.bzl
> -        "go_generated_srcs": go_srcs,
We need to keep the old group for backwards compatibility.

2023-08-22 14:16 UTC, fmeum approved these changes
@linzhp Looks good to me, do you have any concerns about this?

2023-08-24 04:33 UTC, tingilee commented
Closing this with comment:
https://github.com/bazelbuild/rules_go/issues/3664#issuecomment-1690984461

2023-08-24 04:33 UTC, closed without merging